server:
  port: '8000'
  url: 'http://127.0.0.1:8000/'

s3Storage:
  bucket: 'content-service'
  acl: 'public-read'
  url: 'https://content-service.decentraland.zone'

localStorage: 'tmp'

redis:
  address: '127.0.0.1:6379'
  password: ''
  DB: 0
