server:
  port: '8000'                    # Set SERVER_PORT env variable to overwrite this value
  url:  'http://localhost:8000/'  # Set SERVER_URL env variable to overwrite this value

storage:
  storageType: 'LOCAL' # Set STORAGE_TYPE env variable to overwrite this value, Possible values 'REMOTE' and 'LOCAL'
  remoteConfig:
    bucket: ''  # Set AWS_S3_BUCKET env variable to overwrite this value
    url:    ''  # Set AWS_S3_URL env variable to overwrite this value
    acl:    ''  # Set AWS_S3_ACL env variable to overwrite this value
  localPath: 'tmp/' # Set LOCAL_STORAGE_PATH env variable to overwrite this value

redis:
  address:  'localhost:6379' # Set REDIS_ADDRESS env variable to overwrite this value
  password: ''                           # Set REDIS_PASSWORD env variable to overwrite this value
  DB:       0                            # Set REDIS_DB env variable to overwrite this value

decentralandApi:
  landUrl: 'https://api.decentraland.org/v1/' # Set DCL_API env variable to overwrite this value

logLevel: 'DEBUG' # Set LOG_LEVEL env variable to overwrite this value

infura:
  url: 'https://mainnet.infura.io/v3/0720b4fd81a94f9db49ddd00257e1b59'

# This is for New Relic
metrics:
  appName:  '' # Set METRICS_APP env variable to overwrite this value
  appKey:      '' # Set METRICS_KEY env variable to overwrite this value
  analyticsKey: '' # Set ANALYTICS_KEY env variable to overwrite this value

allowedContentTypes:    # Set ALLOWED_TYPES (a comma separated string whit all the types to filer) env variable to overwrite this value. Example 'application/json, image.*'
  - 'application/json'
  - 'image.*'
  - 'application/javascript'
  - 'application/octet-stream'
  - 'audio.*'
  - 'model.*'
  - 'application/xml'
  - 'text.*'

limits:
  parcelSizeLimit: 15000000 # Bytes/Parcel. Set LIMIT_PARCEL_SIZE env variable to overwrite this value
  parcelAssetsLimit: 1000 # Assets/Parcel. Set LIMIT_PARCEL_ASSETS env variable to overwrite this value

workdir: '/tmp' # Set WORK_DIR env variable to overwrite this value

uploadRequestTTL: 600 # Set UPLOAD_TTL env variable to overwrite this value
