server:
  port: '8000'
  url:  'http://localhost:8000/'

storage:
  storageType: 'LOCAL'
  localPath:   'tmp/'

redis:
  address:  'localhost:6379'
  password: ''
  DB:       0

decentralandApi:
  landUrl: 'https://api.decentraland.org/v1/'
