server:
  port: '8000'
  url:  'http://localhost:8000/'

storage:
  storageType: 'LOCAL'
  remoteConfig:
    bucket: ''
    url: ''
    acl: ''
  localPath: '/tmp/'

redis:
  address:  'localhost:6379'
  password: ''
  DB:       0

decentralandApi:
  landUrl: 'https://api.decentraland.zone/v1/'

logLevel: 'INFO'

metrics:
  appName:  ''
  key:      ''
  analyticsKey: ''

allowedContentTypes:
  - 'application/json'
  - 'image.*'
  - 'application/javascript'
  - 'application/octet-stream'
  - 'audio.*'
  - 'model.*'
  - 'application/xml'
  - 'text.*'

limits:
  parcelSizeLimit: 15000000
  parcelAssetsLimit: 1000000

workdir: '/tmp'

uploadRequestTTL: 600