server:
  port: '8000'
  url: 'http://127.0.0.1:8000/'

s3Storage:
  bucket: 'content-service.decentraland.zone'
  acl: 'public-read'
  url: 'https://content-service.decentraland.zone'

localStorage: 'tmp'

redis:
  address: 'content-s-redis-dev.on6tjm.ng.0001.use1.cache.amazonaws.com:6379'
  password: ''
  DB: 0
