server:
  port: '8000'
  url: 'http://localhost:8000/'

s3Storage:
  bucket: '' # Set AWS_S3_BUCKET env variable to overwrite this value
  url: ''    # Set AWS_S3_URL env variable to overwrite this value
  acl: ''    # Set AWS_S3_ACL env variable to overwrite this value

localStorage: 'tmp'

redis:
  address: 'content_service_redis:6379' # Set REDIS_ADDRESS env variable to overwrite this value
  password: ''                          # Set REDIS_PASSWORD env variable to overwrite this value
  DB: 0                                 # Set REDIS_DB env variable to overwrite this value

decentralandApi:
  landUrl: 'https://api.decentraland.org/v1/' # Set DCL_API env variable to overwrite this value
