server:
  hostname: 'localhost'
  port: '8000'

s3Storage:
  bucket: 'content-service'
  acl: 'public-read'
  url: 'https://content-service.decentraland.zone/'

localStorage: 'tmp'

redis:
  address: 'content_service_redis:6379'
  password: ''
  DB: 0
