server:
  port: '8000'
  url: 'http://localhost:8000/'

s3Storage:
  bucket: ''
  acl: ''
  url: ''

localStorage: 'tmp'

redis:
  address: 'localhost:6379'
  password: ''
  DB: 0

decentraland:
  landApi: 'https://api.decentraland.org/v1'
