version: '3'

services:
  golang:
    image: golang:1.11.0
    ports:
      - 8000:8000
    volumes:
      - .:/content-service
      - $GOPATH/pkg/mod:/go/pkg/mod
    environment:
      - GOPATH=/go
    working_dir: /content-service
    command: go run main.go
