server:
  port: '8000'                    # Set SERVER_PORT env variable to overwrite this value
  host: '0.0.0.0'                 # Set SERVER_HOST env variable to overwrite this value

storage:
  bucket: 'local-content'                       # Set AWS_S3_BUCKET env variable to overwrite this value
  url:    'http://localhost:4572/local-content' # Set AWS_S3_URL env variable to overwrite this value
  acl:    'public-read'                         # Set AWS_S3_ACL env variable to overwrite this value

mappings:
  bucket: 'local-mappings'                        # Set MAPPINGS_BUCKET env variable to overwrite this value
  url:    'http://localhost:4572/local-mappings'  # Set MAPPINGS_URL env variable to overwrite this value
  acl:    'public-read'                           # Set MAPPINGS_ACL env variable to overwrite this value

decentralandApi:
  landUrl: 'https://api.decentraland.org/v1/' # Set DCL_API env variable to overwrite this value

logLevel: 'DEBUG' # Set LOG_LEVEL env variable to overwrite this value

rpcconnection:
  url: 'https://mainnet.infura.io/v3/0720b4fd81a94f9db49ddd00257e1b59'

# This is for New Relic
metrics:
  appName:  'content.local' # Set METRICS_APP env variable to overwrite this value
  analyticsKey: '' # Set ANALYTICS_KEY env variable to overwrite this value
  enabled: false  # Set METRICS_ENABLED env variable to overwrite this value

allowedContentTypes:    # Set ALLOWED_TYPES (a comma separated string whit all the types to filer) env variable to overwrite this value. Example 'application/json, image.*'
  - 'application/json'
  - 'image.*'
  - 'application/javascript'
  - 'application/octet-stream'
  - 'audio.*'
  - 'model.*'
  - 'application/xml'
  - 'text.*'

limits:
  parcelSizeLimit: 15000000 # Bytes/Parcel. Set LIMIT_PARCEL_SIZE env variable to overwrite this value
  parcelAssetsLimit: 1000 # Assets/Parcel. Set LIMIT_PARCEL_ASSETS env variable to overwrite this value

uploadRequestTTL: 600 # Set UPLOAD_TTL env variable to overwrite this value
