region = "us-east-1"
env = "stg"
cluster = "cl-worldteam"
execution_role_arn = "arn:aws:iam::872049612737:role/ecsTaskExecutionRole"
security_groups = ["sg-042ee236e279c74a3"]
assign_public_ip = false
alb_container_port = "8000"
alb_container_name = "content-service-golang"
family="td-content-service"
tg_arn=""
